version: "3.9"
services:
  webapi:
    build: ./WebApi
    depends_on:
      - mongodb
    ports:
      - "5001:5001"
    environment:
      - MoviesDatabaseSettings__ConnectionString=mongodb://gbs:geheim@mongodb:27017

  mongodb:
    image: mongo
    volumes:
      - mongoData:/data/db

volumes: 
  mongoData:
